@startuml
'https://plantuml.com/activity-diagram-beta

start

:Load Options;

if(Load All) then(\nyes\n)
    :Load Lists;
endif

while (Close window clicked?) is (\nno)
switch (     List Catalog\n(Loaded Lists Only)\n)

case (user double clicks a list)

    :List Options;
    while(return to lists clicked?) is (\nno)
    switch ( List Options)
    case ( New)
        :Text1;
    case ( Delete)
        :Text2;
    case ( \nEdit)
        :Text3;
    case ( All)
        :Text4;
    case ( Incomplete)
        :Text5;
    case ( Completed)
        :Text6;
    endswitch
    endwhile

case ( Add)
  :Text 1;
case ( Rename)
  :Text 2;
case (\n Delete)
  :Text 3;
case ( Save List)
  :Text 4;
case ( Save All Lists)
  :Text 5;
endswitch

endwhile (yes   )
end


@enduml
